### ISSUE TITLE
Consider revert to an open source license

### ISSUE THREAD

**Issue by niwinz** [tkowalcz/tjahzi#100]
Hello @tkowalcz 

I come to ask you please if you can consider reverting the recent license change.

I understand the motivation behind the change, but on the other side of the hand, this library right now uses a non-standard license and cannot be considered open source.

In my particular case, we are a company based in the US, and we developed a 100% opensource project (penpot) where I was considering using your library/plugin. And in legal terms we can't use this plugin because it would infect the entire code base with that clause.

Also, this additional clause to the MIT license does not seem to have been written or added by a legal team since the restriction is very vague and can be interpreted in many ways, and thus makes it completely unthinkable that small companies that develop open source could consider using it due to uncertainty.
In addition to the main problem, it sets a precedent that later on, more or different clauses may or may not be added with other restrictions on other groups indiscriminately, generating a little more uncertainty.

And morally: there are people in russia who don't give any support to the war but are completely excluded from being able to use this plugin without an obvious reason.

**I fully understand that it is your library and your time that you dedicate and you can license it as you want and when you want. And I respect that, I just wanted to see if there's any chance you could reconsider that change. Politics and opensource are not fighting in the same war and have very different motivations.**

If you finally consider continuing with the modified MIT license, my suggestion is that you make it big and very visible that the plugin is not licensed under an opensource license.

In any case, thank you very much for taking the time to publish this library (even though it is not open source now).

**Comment by tkowalcz** [comment]
I understand your position and appreciate your respectful argumentation. Looks like this license clause makes some harm and nothing good in the end. I'll take this under advisement and let you know shortly.

**Comment by tkowalcz** [comment]
I have reverted to original license and released a new version 0.9.26.

**Comment by niwinz** [comment]
Thank you very much!

**Comment by tkowalcz** [comment]
You are welcome, enjoy.
