### ISSUE TITLE
Debugging tips when appenders are waiting? (log4j)

### ISSUE THREAD

**Issue by sarnobat** [tkowalcz/tjahzi#101]
### Problem

I have 2 appenders, and neither are performing any writes out to their respective targets (file, or Loki index).

### My setup
```
        <RollingFile name="...">
...
        <Loki name="lokiAppender">
...
```

### What I've tried
I believe the root cause is something incorrect in the Loki target kubernetes cluster (which I have little visibility into), but I know that traffic is coming into my log server (after examining `tcpdump` output). And I know there is a connection to Loki (after examining `netstat` output).

I examined the thread dump but neither I nor my colleagues saw anything unusual that points me in the right direction.

I tried wrapping the LokiAppender inside an AsyncAppender thinking that it might handle the heavy load better than the basic appenders alone.

### Question

I see that the LokiAppender source code doesn't have any internal debugging statements so am wondering what is the recommended way to troubleshoot.

### Thread dump
```
$ grep -i state jstack_output.txt | awk '{print $5}' | sort | uniq -c | sort -n
      1 IN_JAVA)
      8 IN_NATIVE)
     37 BLOCKED)
```
```
Thread 27275: (state = IN_JAVA)
 - org.apache.logging.log4j.core.jackson.ContextDataDeserializer.deserialize(com.fasterxml.jackson.core.JsonParser, com.fasterxml.jackson.databind.DeserializationContext) @bci=37, line=62 (Compiled frame; information may be imprecise)
 - org.apache.logging.log4j.core.jackson.ContextDataDeserializer.deserialize(com.fasterxml.jackson.core.JsonParser, com.fasterxml.jackson.databind.DeserializationContext) @bci=3, line=37 (Interpreted frame)
 - org.apache.logging.log4j.core.net.server.InputStreamLogEventBridge.unmarshal(java.lang.String) @bci=5, line=103 (Compiled frame)
 - com.MyProgrammaticLogger.logEvents(java.io.InputStream, org.apache.logging.log4j.core.LogEventListener) @bci=147, line=84 (Compiled frame)
 - org.apache.logging.log4j.core.net.server.UdpSocketServer.run() @bci=77, line=158 (Interpreted frame)
Thread 27272: (state = IN_NATIVE)
```
```
Thread 27265: (state = IN_NATIVE)
 - sun.nio.ch.EPollArrayWrapper.epollWait(long, int, long, int) @bci=0 (Compiled frame; information may be imprecise)
 - sun.nio.ch.EPollArrayWrapper.poll(long) @bci=18, line=269 (Compiled frame)
 - sun.nio.ch.EPollSelectorImpl.doSelect(long) @bci=28, line=93 (Compiled frame)
 - sun.nio.ch.SelectorImpl.lockAndDoSelect(long) @bci=37, line=86 (Compiled frame)
 - sun.nio.ch.SelectorImpl.select(long) @bci=30, line=97 (Compiled frame)
 - pl.tkowalcz.tjahzi.io.netty.channel.nio.SelectedSelectionKeySetSelector.select(long) @bci=12, line=62 (Interpreted frame)
 - pl.tkowalcz.tjahzi.io.netty.channel.nio.NioEventLoop.select(long) @bci=50, line=809 (Interpreted frame)
 - pl.tkowalcz.tjahzi.io.netty.channel.nio.NioEventLoop.run() @bci=85, line=457 (Interpreted frame)
 - pl.tkowalcz.tjahzi.io.netty.util.concurrent.SingleThreadEventExecutor$4.run() @bci=44, line=989 (Interpreted frame)
 - pl.tkowalcz.tjahzi.io.netty.util.internal.ThreadExecutorMap$2.run() @bci=11, line=74 (Interpreted frame)
 - java.lang.Thread.run() @bci=11, line=748 (Interpreted frame)
```
Let me know if you need more info - I'm trying to avoid revealing proprietary info.

**Comment by sarnobat** [comment]
Never mind, this is an issue in my programmatic appender. For the few who might care - the old Log 2.4.1 json format doesn't play nicely with 2.17.X (at least in my code).

**Comment by tkowalcz** [comment]
Thank you for posting the solution, someone might find it indeed useful. As for the logging - you are right. I found myself few times jumping into debugger when in tests Loki did not get any data. I will make a ticket to improve that.
