### ISSUE TITLE
SNI does not seem to be sent in SSL Client Hello packet

### ISSUE THREAD

**Issue by kkalev** [tkowalcz/tjahzi#111]
We have a Loki cluster with multiple Loki installations (each serving a different institution) running as Docker containers with Traefik dynamic proxy as a frontend TCP router.

Usually, when we setup such a cluster we rely on the `Server Name Indicator (SNI)` to route requests to the correct container.

Our general structure is as follows:
* `loki.<institution>.gr` is a CNAME to `loki.<ourdomain>.gr`
* `loki.<ourdomain>.gr` runs a Docker Compose stack of multiple Loki containers and a traefik dynamic proxy/router
* traefik uses the SNI to route requests to the correct container, whitelist IPs and other tasks.
* The Loki endpoint is on port 3100

This setup works with no problems, for example in a similar setup of multiple Grafana installations.

Unfortunately, it seems that the Loki Log4j appender does not use SNI. Capturing the Client Hello with [tcpdump](https://www.baeldung.com/linux/tcpdump-capture-ssl-handshake) and analyzing the packet capture with Wireshark shows no SNI sent to our server. As a result, we have to complicate our setup by having a different endpoint port for each Loki container.

Is there any way to enable SNI? From a quick look at the code it seems that the current answer is no. A few relevant links on how to enable SNI in the Netty library are [here](https://stackoverflow.com/questions/39453541/configure-netty-ssl-client-sockets-to-send-sni-header-in-android) and [here](https://github.com/netty/netty/issues/9643#issuecomment-539485574).

Is it possible to add/enable this feature? It would be more than helpful in multi-homed setups.

Thank you for a very helpful and quality product.

**Comment by tkowalcz** [comment]
Thank you for your interest in this library. Sorry I was unable to respond earlier. I'll look into SNI and will try to come up with an implementation soon.

**Comment by tkowalcz** [comment]
I have implemented SNI. Tested using NGINX with two "server" definitions that route two different Loki instances. Seems to work as expected.
