### ISSUE TITLE
[log4j2-appender] send log timestamp when using JsonTemplateLayout

### ISSUE THREAD

**Issue by mert-kirpici** [tkowalcz/tjahzi#127]
Hi, please point me in the right direction if this already exists or it is the default behavior.

I am trying to use the log4j2-appender to send my java application logs to loki. I would like to be able to:
- use structured logging via apache log4j2's JsonTemplateLayout
- **not** use the ingestion time for logs but use the log creation timestamp(must be sent to loki by the appender i assume?)
- **not** include the timestamp in the json body if possible, as it will be a redundant field. But this is not a huge problem, if the only way to make this happen is to select the key that contains the timestamp in the log object.

running versions:
- loki 3.1.1
- log4j2-bom 2.24.0
- log4j2-appender-nodep 0.9.32

**Comment by tkowalcz** [comment]
I think this can be achieved. I created following config:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration packages="pl.tkowalcz.tjahzi.log4j2" status="DEBUG">
    <Loggers>
        <Root level="OFF">
        </Root>

        <Logger name="pl.tkowalcz" level="ALL">
            <AppenderRef ref="Loki"/>
        </Logger>
    </Loggers>

    <appenders>
        <Loki name="Loki">
            <host>${sys:loki.host}</host>
            <port>${sys:loki.port}</port>

            <JsonTemplateLayout eventTemplateUri="classpath:MyLayout.json"/>

            <Header name="server" value="127.0.0.1"/>
            <Label name="server" value="127.0.0.1"/>
        </Loki>
    </appenders>
</configuration>
```

and `MyLayout.json` was copied from `JsonTemplate` documentation. I just removed the timestamp field:

```json
{
  "someConstant": 1,
  "message": {
    "$resolver": "message",
    "stringified": true
  }
}
```

This generates following entry in Loki (when queried using rest api):
```json
  "result": [
            {
                "stream": {
                    "server": "127.0.0.1",
                    "service_name": "unknown_service"
                },
                "values": [
                    [
                        "1726520192716914000",
                        "{\"someConstant\":1,\"message\":\"Hello World\"}\n"
                    ]
                ]
            }
        ],
```

As you can see there is a timestamp derived from the time the log was sent to Loki. In the UI it looks like this:

<img width="1028" alt="image" src="https://github.com/user-attachments/assets/0bd4f1ea-9612-431f-ac18-b91173613918">


Is this what you were after?

**Comment by mert-kirpici** [comment]
Hey, thanks for the quick response. If I am not mistaken this is the timestamp when the log was sent to loki, not when it was created by my application. I was wondering if there is a way to send the actual timestamp when the log event happened.

I think promtail has way of doing this:
https://grafana.com/docs/loki/latest/send-data/promtail/stages/timestamp/

**Comment by tkowalcz** [comment]
The timestamp is taken from the log4j2 event:

```java
event.getInstant().getEpochMillisecond()
event.getInstant().getNanoOfMillisecond()
```

at the time it was created in log4j2. It is then sent to Loki alongside the contents of the message regardless if the message itself contains any time information. Loki documentation does not state it clearly but I did a test and set nanosecond part to `42` inside Tjahzi appender and this is what I now get:

```json
                "values": [
                    [
                        "1726521489367000042",
                        "{\"instant\":\"2024-09-16T21:18:09.367Z\",\"someConstant\":1,\"message\":\"Hello World\"}\n"
                    ]
                ]
```

**Comment by mert-kirpici** [comment]
oh, great then. I believe we can close this issue. thanks for checking it out!
