### ISSUE TITLE
Dynamic label substitution

### ISSUE THREAD

**Issue by hijackit** [tkowalcz/tjahzi#47]
Hello again :)

I'm posting this after having read this:
> Lookups / variable substitution
Contents of the properties are automatically interpolated by Log4j2 (see here). All environment, system etc. variable references will be replaced by their values during initialization of the appender. Alternatively this process could have been executed for every log message. The latter approach was deemed too expensive. If you need a mechanism to replace a variable after logging system initialization I would lvie to hear your use case - please file an issue.

I'll do my best to explain our use case: we have a distributed multi-tenant application (many running application instances, each one serving different tenants) and we would like to attach a "tenant" label to each message, in order to easily group messages (potentially produced by different instances) but all belonging to the same tenant.

For now, we will simply log the tenant in each message payload (using MDC/ThreadContext), but it would be great to take advantage of Loki labels to make it easier when it comes to monitoring. 
An idea would be to be able to write something like this:
`<Label name="tenant" value="${ctx:tenant}"/>`

I also understand that there is a possible impact in terms of performance having to evaluate the label every message.

**Comment by tkowalcz** [comment]
Just to let you know that I am working on this. I am using log4j2 standard string interpolator and should have a new release this week.

For the future I would like to create custom, allocation free interpolator - it seems like a fun project ;)

**Comment by tkowalcz** [comment]
Release `0.9.10` introduces this feature for ctx lookup. I have not yet tested it on production cluster, but this release has all relevant unit and integration tests.
