### ISSUE TITLE
Patterns in lables

### ISSUE THREAD

**Issue by paradoxxl** [tkowalcz/tjahzi#56]
It is possible to use pattens such as **%C{1.}** as values in labels which are then dynamically resolved?

**Comment by tkowalcz** [comment]
Right now it is not possible. Only MDC lookups `${ctx:}` are supported. There are two reasons:

1. Tjahzi is performance oriented so I want to make sure every feature like the is implemented with no allocations.
2. Loki does not like high cardinality labels so I did not consider dynamically generated labels to be an important feature.

If you have some specific patterns you would like me to support then please list them but I can't promise when that will happen.

**Comment by paradoxxl** [comment]
Thank you for clarification. This seems quite reasonable.

For logging monolithic applications, the origin of the message could be an equivalent of using something like an 'app'-label for a distributed application. Therefore, **class** or **logger** could be quite valuable label for improving search performance. 

What do you think about this?

**Comment by tkowalcz** [comment]
It sounds very reasonable. I'll take a look and will keep you posted.

**Comment by tkowalcz** [comment]
Newest release `0.9.13` uses PatternLayout to implement dynamic label value generation. 

I have marked it as pre release until I have some prod deployments with it.
