### ISSUE TITLE
Sample Programmatic Configuration for Loki Log4j2 Appender using Configuration Builder

### ISSUE THREAD

**Issue by akhilvpsharma** [tkowalcz/tjahzi#64]
http://logging.apache.org/log4j/2.x/manual/customconfig.html
I wish to enable or disable the connection to Loki via Environment variables. So trying programmatic configuration. Unable to get it running. Request to provide a sample of it if possible.

**Comment by tkowalcz** [comment]
Hi,

I am not very familiar with programmatic configuration of Log4j. Can you provide a sample code of what you are doing? How do "Environment variables" tie to this?

**Comment by akhilvpsharma** [comment]
I am basically trying to avoid connection to Loki, if a property like 'enable_loki = False' (either in application.properties or Environment variable) is set. This doesn't seem possible via xml configuration file, so I tried my hands on programmatic configuration for Log 4j as shown here http://logging.apache.org/log4j/2.x/manual/customconfig.html . 
I was able to set up Console and File Appenders, but struggling with Loki Appender.

**Comment by hijackit** [comment]
Don't know if this can help you: with the following configuration I can turn loki logging on/off based on an environment variable (here I used LOG_TO). 
I achieved this with the routing feature of log4j2.

* if LOG_TO == CONSOLE (or if LOG_TO is not set), then it will use the console appender; 
* if LOG_TO == LOKI, then it will rout everything to the loki appender.

```
<Appenders>
  <Loki name="LOKI">
    ...
  </Loki>

  <Console name="CONSOLE" target="SYSTEM_OUT">
    ...
  </Console >

  <Routing name="ROUTER">
    <Routes pattern="$${env:LOG_TO:-CONSOLE}">
      <Route ref="LOKI" key="LOKI" />
      <Route ref="CONSOLE" key="CONSOLE" />
    </Routes>
  </Routing>
</Appenders>
```

**Comment by tkowalcz** [comment]
@hijackit thanks for the tip.

@akhilvpsharma I wrote a test using programmatic config (builder) and does not initialise Loki properly. I will investigate it further.

**Comment by tkowalcz** [comment]
@akhilvpsharma I was able to setup Loki programmatically. Here is some documentation: https://github.com/tkowalcz/tjahzi/wiki/Dynamic-configuration. It also links to a junit test that does it.

**Comment by akhilvpsharma** [comment]
@hijackit Thank you for the tip!
@tkowalcz Thanks a lot for the documentation. Really helpful.
