### ISSUE TITLE
race condition in Log4jAdapterLabelPrinter

### ISSUE THREAD

**Issue by thgau** [tkowalcz/tjahzi#74]
There is a problem with multiple threads in class Log4jAdapterLabelPrinter.
The StringBuilder allocated there is shared between threads. It might happen that the threads corrupt the data if both are using it at the same time.
I think the StringBuffer should be allocated once per Thread and kept in a ThreadLocal storage.
Best Regards, 
thgau

**Comment by tkowalcz** [comment]
Hi,

thanks a lot for reporting. I can confirm it, and it is quite obvious when someone points it out. I will try to push a fix today.
