### ISSUE TITLE
How to find logs in Grafana Cloud

### ISSUE THREAD

**Issue by PrimeDominus** [tkowalcz/tjahzi#84]
We have had success using Promtail to get logs from our Java app log files. For Promtail we have called the _Job_ `log4j`, and when using this panel <https://grafana.com/grafana/dashboards/13639> which we have imported, we can see the logs by entering `log4j` in the _App_ field.

I believe this is similar to entering `{job="log4j"}` in the Log browser of Grafana > Explore

For reference, our `scrape_configs` section of our Promtail config.yaml is like the below:
```yaml
scrape_configs:
- job_name: app
  static_configs:
  - targets:
      - localhost
    labels:
      job: log4j
      __path__: ../logs/*.log
```

How do we set the _job_ value in the XML file for the Tjahzi log4j2 appender? Or, more broadly, how are we to view these logs in Grafana Cloud?

For reference, our xml file looks very similar to the below:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration packages="pl.tkowalcz.tjahzi.log4j2">
    <Loggers>
        <Root level="INFO">
            <AppenderRef ref="Loki"/>
        </Root>
    </Loggers>

    <appenders>
        <Loki name="Loki">
            <host>grafanaCloudHostSameAsWhatweUseInPromtail(without https:// at the front)</host>
            <port>443</port>
	    <username>usernameSameAsWhatweUseInPromtail</username>
            <password>passwordSameAsWhatweUseInPromtail</password>

            <PatternLayout>
                <Pattern>%X{tid} [%t] %d{MM-dd HH:mm:ss.SSS} %5p %c{1} - %m%n%exception{full}</Pattern>
            </PatternLayout>

            <Label name="server" value="127.0.0.1"/>
        </Loki>
    </appenders>
</configuration>

**Comment by tkowalcz** [comment]
Hello,

you need to use label:

```xml
 <Label name="job" value="log4j"/>
```

There is a test [GrafanaCloudAppenderTest](https://github.com/tkowalcz/tjahzi/blob/master/log4j2-appender/src/test/java/pl/tkowalcz/tjahzi/log4j2/GrafanaCloudAppenderTest.java) that sends data to Grafana cloud using this [configuration](https://github.com/tkowalcz/tjahzi/blob/master/log4j2-appender/src/test/resources/grafana-cloud-appender-test-configuration.xml).

I have modified it to include label `job=log4j`. This will result in following labels being available in Loki:

![image](https://user-images.githubusercontent.com/309611/148124431-82676aa8-7b51-48e1-a72f-42c94b6438e4.png)
![image](https://user-images.githubusercontent.com/309611/148124076-432b3f5c-8c59-4175-805d-d8110b17e3b9.png)

**Comment by PrimeDominus** [comment]
Thank you. This works.
