### ISSUE TITLE
passing parameter instead of hard coded value for url

### ISSUE THREAD

**Issue by amiraziz** [tkowalcz/tjahzi#98]
Hi tkowalcz, 

I saw in your sample that you used for example ${sys:loki.url}  instead of real value in loki appendar in log4j example.  [log4j2-appender/README.md](https://github.com/tkowalcz/tjahzi/blob/280229471312ec1a0cc0f9b40d025fb328294e28/log4j2-appender/README.md)

i need to use something like this with passing config from spring boot yaml file. but i don't know how can pass parameter to log4j2 context to detect real value same your usage. although i don't know how you fill ${sys:loki.host} value in your example.

Thank you for helping me.

**Comment by tkowalcz** [comment]
Hi,

[this](https://logging.apache.org/log4j/log4j-2.2/manual/configuration.html#PropertySubstitution) is part of the documentation of log4j that describes how properties are interpolated. In a nutshell, the prefix `sys`, `map`, `ctx` etc. tells the logging system where to look for the property. In case of sys it will look at "system properties", if you use "env" then it will look at environment variables.

I never used Spring Boot with Loki but according to [this](https://logging.apache.org/log4j/2.x/log4j-spring-boot/index.html) documentation there is special integration and you can use `spring` to lookup values via spring boot.
